#!/bin/bash

set -o errexit # script exits when a command fails == set -e
set -o nounset # script exits when tries to use undeclared variables == set -u
set -o pipefail # causes pipelines to retain / set the last non-zero status

export ATLAS_CLOUD_TOKEN=$(buildkite-agent secret get ATLAS_CLOUD_TOKEN)
echo "Set token" $ATLAS_CLOUD_TOKEN

exit 0
